version: '3.8'

services:
  voicechat:
    image: rismotemch/voicechat:latest
    container_name: voicechat
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=8080
      - DOMAIN=voice.repozis.ru
      - ENVIRONMENT=production
      - ROOM_NAME=main
      - MAX_USERS=25
      - UDP_MIN=50000
      - UDP_MAX=51000
      - STUN_SERVERS=stun:stun.l.google.com:19302,stun:stun1.l.google.com:19302
      - TURN_SERVERS=turn:voice.repozis.ru:3478
      - REQUIRE_AUTH=false
      - LOG_LEVEL=debug
      - LOG_FORMAT=json
      - UPLOAD_PATH=/app/data/uploads
      - MAX_UPLOAD_SIZE=104857600
    volumes:
      - ./data:/app/data