name: Deploy Self-Hosted

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Deploy
        run: |
          cd /opt/voicechat
          git reset --hard
          git pull
          docker stop voicechat || true
          docker rm voicechat || true
          docker compose build --no-cache
          docker compose up -d